<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_task_plan  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_task_plan' );		 }	    
	    		public function getPlan_id(){			 return self::$_data ['plan_id']; 		}		public function getBid_id(){			 return self::$_data ['bid_id']; 		}		public function getTask_id(){			 return self::$_data ['task_id']; 		}		public function getPlan_title(){			 return self::$_data ['plan_title']; 		}		public function getPlan_desc(){			 return self::$_data ['plan_desc']; 		}		public function getPlan_step(){			 return self::$_data ['plan_step']; 		}		public function getPlan_amount(){			 return self::$_data ['plan_amount']; 		}		public function getPlan_status(){			 return self::$_data ['plan_status']; 		}		public function getStart_time(){			 return self::$_data ['start_time']; 		}		public function getEnd_time(){			 return self::$_data ['end_time']; 		}		public function getOver_time(){			 return self::$_data ['over_time']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setPlan_id($value){ 			 self::$_data ['plan_id'] = $value;			 return $this ; 		}		public function setBid_id($value){ 			 self::$_data ['bid_id'] = $value;			 return $this ; 		}		public function setTask_id($value){ 			 self::$_data ['task_id'] = $value;			 return $this ; 		}		public function setPlan_title($value){ 			 self::$_data ['plan_title'] = $value;			 return $this ; 		}		public function setPlan_desc($value){ 			 self::$_data ['plan_desc'] = $value;			 return $this ; 		}		public function setPlan_step($value){ 			 self::$_data ['plan_step'] = $value;			 return $this ; 		}		public function setPlan_amount($value){ 			 self::$_data ['plan_amount'] = $value;			 return $this ; 		}		public function setPlan_status($value){ 			 self::$_data ['plan_status'] = $value;			 return $this ; 		}		public function setStart_time($value){ 			 self::$_data ['start_time'] = $value;			 return $this ; 		}		public function setEnd_time($value){ 			 self::$_data ['end_time'] = $value;			 return $this ; 		}		public function setOver_time($value){ 			 self::$_data ['over_time'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_task_plan  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_task_plan		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['plan_id'] )) { 						self::$_where = array ('plan_id' => self::$_data ['plan_id'] );						unset(self::$_data['plan_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_task_plan,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_task_plan records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_task_plan, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where plan_id = $this->_plan_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 