<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_task_wbdj_work  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_task_wbdj_work' );		 }	    
	    		public function getDjwk_id(){			 return self::$_data ['djwk_id']; 		}		public function getTask_id(){			 return self::$_data ['task_id']; 		}		public function getWork_id(){			 return self::$_data ['work_id']; 		}		public function getWb_type(){			 return self::$_data ['wb_type']; 		}		public function getClick_num(){			 return self::$_data ['click_num']; 		}		public function getWb_url(){			 return self::$_data ['wb_url']; 		}		public function getJump_url(){			 return self::$_data ['jump_url']; 		}		public function getWb_account(){			 return self::$_data ['wb_account']; 		}		public function getWb_sid(){			 return self::$_data ['wb_sid']; 		}		public function getGet_cash(){			 return self::$_data ['get_cash']; 		}		public function getWb_data(){			 return self::$_data ['wb_data']; 		}		public function getIp(){			 return self::$_data ['ip']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setDjwk_id($value){ 			 self::$_data ['djwk_id'] = $value;			 return $this ; 		}		public function setTask_id($value){ 			 self::$_data ['task_id'] = $value;			 return $this ; 		}		public function setWork_id($value){ 			 self::$_data ['work_id'] = $value;			 return $this ; 		}		public function setWb_type($value){ 			 self::$_data ['wb_type'] = $value;			 return $this ; 		}		public function setClick_num($value){ 			 self::$_data ['click_num'] = $value;			 return $this ; 		}		public function setWb_url($value){ 			 self::$_data ['wb_url'] = $value;			 return $this ; 		}		public function setJump_url($value){ 			 self::$_data ['jump_url'] = $value;			 return $this ; 		}		public function setWb_account($value){ 			 self::$_data ['wb_account'] = $value;			 return $this ; 		}		public function setWb_sid($value){ 			 self::$_data ['wb_sid'] = $value;			 return $this ; 		}		public function setGet_cash($value){ 			 self::$_data ['get_cash'] = $value;			 return $this ; 		}		public function setWb_data($value){ 			 self::$_data ['wb_data'] = $value;			 return $this ; 		}		public function setIp($value){ 			 self::$_data ['ip'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_task_wbdj_work  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_task_wbdj_work		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['ip'] )) { 						self::$_where = array ('ip' => self::$_data ['ip'] );						unset(self::$_data['ip']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_task_wbdj_work,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_task_wbdj_work records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_task_wbdj_work, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where ip = $this->_ip "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 