<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_order_detail  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_order_detail' );		 }	    
	    		public function getDetail_id(){			 return self::$_data ['detail_id']; 		}		public function getDetail_name(){			 return self::$_data ['detail_name']; 		}		public function getOrder_id(){			 return self::$_data ['order_id']; 		}		public function getObj_type(){			 return self::$_data ['obj_type']; 		}		public function getObj_id(){			 return self::$_data ['obj_id']; 		}		public function getPrice(){			 return self::$_data ['price']; 		}		public function getNum(){			 return self::$_data ['num']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setDetail_id($value){ 			 self::$_data ['detail_id'] = $value;			 return $this ; 		}		public function setDetail_name($value){ 			 self::$_data ['detail_name'] = $value;			 return $this ; 		}		public function setOrder_id($value){ 			 self::$_data ['order_id'] = $value;			 return $this ; 		}		public function setObj_type($value){ 			 self::$_data ['obj_type'] = $value;			 return $this ; 		}		public function setObj_id($value){ 			 self::$_data ['obj_id'] = $value;			 return $this ; 		}		public function setPrice($value){ 			 self::$_data ['price'] = $value;			 return $this ; 		}		public function setNum($value){ 			 self::$_data ['num'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_order_detail  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_order_detail		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['detail_id'] )) { 						self::$_where = array ('detail_id' => self::$_data ['detail_id'] );						unset(self::$_data['detail_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_order_detail,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_order_detail records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_order_detail, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where detail_id = $this->_detail_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 