<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_order  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_order' );		 }	    
	    		public function getOrder_id(){			 return self::$_data ['order_id']; 		}		public function getOrder_name(){			 return self::$_data ['order_name']; 		}		public function getOrder_time(){			 return self::$_data ['order_time']; 		}		public function getOrder_amount(){			 return self::$_data ['order_amount']; 		}		public function getOrder_status(){			 return self::$_data ['order_status']; 		}		public function getOrder_body(){			 return self::$_data ['order_body']; 		}		public function getOrder_uid(){			 return self::$_data ['order_uid']; 		}		public function getOrder_username(){			 return self::$_data ['order_username']; 		}		public function getSeller_uid(){			 return self::$_data ['seller_uid']; 		}		public function getSeller_username(){			 return self::$_data ['seller_username']; 		}		public function getModel_id(){			 return self::$_data ['model_id']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setOrder_id($value){ 			 self::$_data ['order_id'] = $value;			 return $this ; 		}		public function setOrder_name($value){ 			 self::$_data ['order_name'] = $value;			 return $this ; 		}		public function setOrder_time($value){ 			 self::$_data ['order_time'] = $value;			 return $this ; 		}		public function setOrder_amount($value){ 			 self::$_data ['order_amount'] = $value;			 return $this ; 		}		public function setOrder_status($value){ 			 self::$_data ['order_status'] = $value;			 return $this ; 		}		public function setOrder_body($value){ 			 self::$_data ['order_body'] = $value;			 return $this ; 		}		public function setOrder_uid($value){ 			 self::$_data ['order_uid'] = $value;			 return $this ; 		}		public function setOrder_username($value){ 			 self::$_data ['order_username'] = $value;			 return $this ; 		}		public function setSeller_uid($value){ 			 self::$_data ['seller_uid'] = $value;			 return $this ; 		}		public function setSeller_username($value){ 			 self::$_data ['seller_username'] = $value;			 return $this ; 		}		public function setModel_id($value){ 			 self::$_data ['model_id'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_order  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_order		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['order_id'] )) { 						self::$_where = array ('order_id' => self::$_data ['order_id'] );						unset(self::$_data['order_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_order,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_order records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_order, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where order_id = $this->_order_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 