<?php
  $pay_basic=array("pay_name"=>"易宝",
  					 "type"=>"online",
                     "pay_dir"=>"yeepay",
                     "pay_dev"=>"kekezu",
                     "pay_desc"=>"易宝接口",
                     "img"=>"tenpay.gif",
                     "initparam"=>"pid:商户编号;key:交易密钥"
               );
//商户编号p1_MerId,以及密钥
?>