<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_mark  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_mark' );		 }	    
	    		public function getMark_id(){			 return self::$_data ['mark_id']; 		}		public function getModel_code(){			 return self::$_data ['model_code']; 		}		public function getOrigin_id(){			 return self::$_data ['origin_id']; 		}		public function getObj_id(){			 return self::$_data ['obj_id']; 		}		public function getObj_cash(){			 return self::$_data ['obj_cash']; 		}		public function getMark_status(){			 return self::$_data ['mark_status']; 		}		public function getMark_content(){			 return self::$_data ['mark_content']; 		}		public function getMark_time(){			 return self::$_data ['mark_time']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getUsername(){			 return self::$_data ['username']; 		}		public function getMark_max_time(){			 return self::$_data ['mark_max_time']; 		}		public function getBy_uid(){			 return self::$_data ['by_uid']; 		}		public function getBy_username(){			 return self::$_data ['by_username']; 		}		public function getAid(){			 return self::$_data ['aid']; 		}		public function getAid_star(){			 return self::$_data ['aid_star']; 		}		public function getMark_value(){			 return self::$_data ['mark_value']; 		}		public function getMark_type(){			 return self::$_data ['mark_type']; 		}		public function getMark_count(){			 return self::$_data ['mark_count']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setMark_id($value){ 			 self::$_data ['mark_id'] = $value;			 return $this ; 		}		public function setModel_code($value){ 			 self::$_data ['model_code'] = $value;			 return $this ; 		}		public function setOrigin_id($value){ 			 self::$_data ['origin_id'] = $value;			 return $this ; 		}		public function setObj_id($value){ 			 self::$_data ['obj_id'] = $value;			 return $this ; 		}		public function setObj_cash($value){ 			 self::$_data ['obj_cash'] = $value;			 return $this ; 		}		public function setMark_status($value){ 			 self::$_data ['mark_status'] = $value;			 return $this ; 		}		public function setMark_content($value){ 			 self::$_data ['mark_content'] = $value;			 return $this ; 		}		public function setMark_time($value){ 			 self::$_data ['mark_time'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setUsername($value){ 			 self::$_data ['username'] = $value;			 return $this ; 		}		public function setMark_max_time($value){ 			 self::$_data ['mark_max_time'] = $value;			 return $this ; 		}		public function setBy_uid($value){ 			 self::$_data ['by_uid'] = $value;			 return $this ; 		}		public function setBy_username($value){ 			 self::$_data ['by_username'] = $value;			 return $this ; 		}		public function setAid($value){ 			 self::$_data ['aid'] = $value;			 return $this ; 		}		public function setAid_star($value){ 			 self::$_data ['aid_star'] = $value;			 return $this ; 		}		public function setMark_value($value){ 			 self::$_data ['mark_value'] = $value;			 return $this ; 		}		public function setMark_type($value){ 			 self::$_data ['mark_type'] = $value;			 return $this ; 		}		public function setMark_count($value){ 			 self::$_data ['mark_count'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_mark  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_mark		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['mark_id'] )) { 						self::$_where = array ('mark_id' => self::$_data ['mark_id'] );						unset(self::$_data['mark_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_mark,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_mark records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_mark, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where mark_id = $this->_mark_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 