<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_industry  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_industry' );		 }	    
	    		public function getIndus_id(){			 return self::$_data ['indus_id']; 		}		public function getIndus_pid(){			 return self::$_data ['indus_pid']; 		}		public function getIndus_name(){			 return self::$_data ['indus_name']; 		}		public function getIs_recommend(){			 return self::$_data ['is_recommend']; 		}		public function getIndus_type(){			 return self::$_data ['indus_type']; 		}		public function getListorder(){			 return self::$_data ['listorder']; 		}		public function getOn_time(){			 return self::$_data ['on_time']; 		}		public function getList_type(){			 return self::$_data ['list_type']; 		}		public function getList_tpl(){			 return self::$_data ['list_tpl']; 		}		public function getIndus_intro(){			 return self::$_data ['indus_intro']; 		}		public function getList_desc(){			 return self::$_data ['list_desc']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setIndus_id($value){ 			 self::$_data ['indus_id'] = $value;			 return $this ; 		}		public function setIndus_pid($value){ 			 self::$_data ['indus_pid'] = $value;			 return $this ; 		}		public function setIndus_name($value){ 			 self::$_data ['indus_name'] = $value;			 return $this ; 		}		public function setIs_recommend($value){ 			 self::$_data ['is_recommend'] = $value;			 return $this ; 		}		public function setIndus_type($value){ 			 self::$_data ['indus_type'] = $value;			 return $this ; 		}		public function setListorder($value){ 			 self::$_data ['listorder'] = $value;			 return $this ; 		}		public function setOn_time($value){ 			 self::$_data ['on_time'] = $value;			 return $this ; 		}		public function setList_type($value){ 			 self::$_data ['list_type'] = $value;			 return $this ; 		}		public function setList_tpl($value){ 			 self::$_data ['list_tpl'] = $value;			 return $this ; 		}		public function setIndus_intro($value){ 			 self::$_data ['indus_intro'] = $value;			 return $this ; 		}		public function setList_desc($value){ 			 self::$_data ['list_desc'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_industry  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_industry		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['indus_id'] )) { 						self::$_where = array ('indus_id' => self::$_data ['indus_id'] );						unset(self::$_data['indus_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_industry,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_industry records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_industry, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where indus_id = $this->_indus_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 