<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_cron  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_cron' );		 }	    
	    		public function getCron_id(){			 return self::$_data ['cron_id']; 		}		public function getCron_name(){			 return self::$_data ['cron_name']; 		}		public function getSpan(){			 return self::$_data ['span']; 		}		public function getNextruntime(){			 return self::$_data ['nextruntime']; 		}		public function getAllow(){			 return self::$_data ['allow']; 		}		public function getFilename(){			 return self::$_data ['filename']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setCron_id($value){ 			 self::$_data ['cron_id'] = $value;			 return $this ; 		}		public function setCron_name($value){ 			 self::$_data ['cron_name'] = $value;			 return $this ; 		}		public function setSpan($value){ 			 self::$_data ['span'] = $value;			 return $this ; 		}		public function setNextruntime($value){ 			 self::$_data ['nextruntime'] = $value;			 return $this ; 		}		public function setAllow($value){ 			 self::$_data ['allow'] = $value;			 return $this ; 		}		public function setFilename($value){ 			 self::$_data ['filename'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_cron  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_cron		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['cron_id'] )) { 						self::$_where = array ('cron_id' => self::$_data ['cron_id'] );						unset(self::$_data['cron_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_cron,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_cron records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_cron, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where cron_id = $this->_cron_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 