<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_field  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_field' );		 }	    
	    		public function getField_id(){			 return self::$_data ['field_id']; 		}		public function getField_type(){			 return self::$_data ['field_type']; 		}		public function getField_name(){			 return self::$_data ['field_name']; 		}		public function getField_items(){			 return self::$_data ['field_items']; 		}		public function getField_table(){			 return self::$_data ['field_table']; 		}		public function getField_description(){			 return self::$_data ['field_description']; 		}		public function getValid(){			 return self::$_data ['valid']; 		}		public function getValid_require(){			 return self::$_data ['valid_require']; 		}		public function getValid_min(){			 return self::$_data ['valid_min']; 		}		public function getValid_max(){			 return self::$_data ['valid_max']; 		}		public function getValid_type(){			 return self::$_data ['valid_type']; 		}		public function getField_errordesc(){			 return self::$_data ['field_errordesc']; 		}		public function getListorder(){			 return self::$_data ['listorder']; 		}		public function getDateline(){			 return self::$_data ['dateline']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setField_id($value){ 			 self::$_data ['field_id'] = $value;			 return $this ; 		}		public function setField_type($value){ 			 self::$_data ['field_type'] = $value;			 return $this ; 		}		public function setField_name($value){ 			 self::$_data ['field_name'] = $value;			 return $this ; 		}		public function setField_items($value){ 			 self::$_data ['field_items'] = $value;			 return $this ; 		}		public function setField_table($value){ 			 self::$_data ['field_table'] = $value;			 return $this ; 		}		public function setField_description($value){ 			 self::$_data ['field_description'] = $value;			 return $this ; 		}		public function setValid($value){ 			 self::$_data ['valid'] = $value;			 return $this ; 		}		public function setValid_require($value){ 			 self::$_data ['valid_require'] = $value;			 return $this ; 		}		public function setValid_min($value){ 			 self::$_data ['valid_min'] = $value;			 return $this ; 		}		public function setValid_max($value){ 			 self::$_data ['valid_max'] = $value;			 return $this ; 		}		public function setValid_type($value){ 			 self::$_data ['valid_type'] = $value;			 return $this ; 		}		public function setField_errordesc($value){ 			 self::$_data ['field_errordesc'] = $value;			 return $this ; 		}		public function setListorder($value){ 			 self::$_data ['listorder'] = $value;			 return $this ; 		}		public function setDateline($value){ 			 self::$_data ['dateline'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_field  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_field		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['field_id'] )) { 						self::$_where = array ('field_id' => self::$_data ['field_id'] );						unset(self::$_data['field_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_field,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_field records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_field, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where field_id = $this->_field_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 