<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_favorite  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_favorite' );		 }	    
	    		public function getF_id(){			 return self::$_data ['f_id']; 		}		public function getKeep_type(){			 return self::$_data ['keep_type']; 		}		public function getObj_type(){			 return self::$_data ['obj_type']; 		}		public function getOrigin_id(){			 return self::$_data ['origin_id']; 		}		public function getObj_id(){			 return self::$_data ['obj_id']; 		}		public function getObj_name(){			 return self::$_data ['obj_name']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getUsername(){			 return self::$_data ['username']; 		}		public function getOn_date(){			 return self::$_data ['on_date']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setF_id($value){ 			 self::$_data ['f_id'] = $value;			 return $this ; 		}		public function setKeep_type($value){ 			 self::$_data ['keep_type'] = $value;			 return $this ; 		}		public function setObj_type($value){ 			 self::$_data ['obj_type'] = $value;			 return $this ; 		}		public function setOrigin_id($value){ 			 self::$_data ['origin_id'] = $value;			 return $this ; 		}		public function setObj_id($value){ 			 self::$_data ['obj_id'] = $value;			 return $this ; 		}		public function setObj_name($value){ 			 self::$_data ['obj_name'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setUsername($value){ 			 self::$_data ['username'] = $value;			 return $this ; 		}		public function setOn_date($value){ 			 self::$_data ['on_date'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_favorite  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_favorite		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['f_id'] )) { 						self::$_where = array ('f_id' => self::$_data ['f_id'] );						unset(self::$_data['f_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_favorite,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_favorite records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_favorite, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where f_id = $this->_f_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 