<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_auth_enterprise  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_auth_enterprise' );		 }	    
	    		public function getUid(){			 return self::$_data ['uid']; 		}		public function getUsername(){			 return self::$_data ['username']; 		}		public function getCompany(){			 return self::$_data ['company']; 		}		public function getLicen_num(){			 return self::$_data ['licen_num']; 		}		public function getLicen_pic(){			 return self::$_data ['licen_pic']; 		}		public function getCash(){			 return self::$_data ['cash']; 		}		public function getStart_time(){			 return self::$_data ['start_time']; 		}		public function getEnd_time(){			 return self::$_data ['end_time']; 		}		public function getAuth_status(){			 return self::$_data ['auth_status']; 		}		public function getLegal(){			 return self::$_data ['legal']; 		}		public function getStaff_num(){			 return self::$_data ['staff_num']; 		}		public function getRun_years(){			 return self::$_data ['run_years']; 		}		public function getUrl(){			 return self::$_data ['url']; 		}		public function getId_code(){			 return self::$_data ['id_code']; 		}		public function getId_pic(){			 return self::$_data ['id_pic']; 		}		public function getPic(){			 return self::$_data ['pic']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setUsername($value){ 			 self::$_data ['username'] = $value;			 return $this ; 		}		public function setCompany($value){ 			 self::$_data ['company'] = $value;			 return $this ; 		}		public function setLicen_num($value){ 			 self::$_data ['licen_num'] = $value;			 return $this ; 		}		public function setLicen_pic($value){ 			 self::$_data ['licen_pic'] = $value;			 return $this ; 		}		public function setCash($value){ 			 self::$_data ['cash'] = $value;			 return $this ; 		}		public function setStart_time($value){ 			 self::$_data ['start_time'] = $value;			 return $this ; 		}		public function setEnd_time($value){ 			 self::$_data ['end_time'] = $value;			 return $this ; 		}		public function setAuth_status($value){ 			 self::$_data ['auth_status'] = $value;			 return $this ; 		}		public function setLegal($value){ 			 self::$_data ['legal'] = $value;			 return $this ; 		}		public function setStaff_num($value){ 			 self::$_data ['staff_num'] = $value;			 return $this ; 		}		public function setRun_years($value){ 			 self::$_data ['run_years'] = $value;			 return $this ; 		}		public function setUrl($value){ 			 self::$_data ['url'] = $value;			 return $this ; 		}		public function setId_code($value){ 			 self::$_data ['id_code'] = $value;			 return $this ; 		}		public function setId_pic($value){ 			 self::$_data ['id_pic'] = $value;			 return $this ; 		}		public function setPic($value){ 			 self::$_data ['pic'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_auth_enterprise  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_auth_enterprise		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['uid'] )) { 						self::$_where = array ('uid' => self::$_data ['uid'] );						unset(self::$_data['uid']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_auth_enterprise,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_auth_enterprise records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_auth_enterprise, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where uid = $this->_uid "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 