<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_member_work  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_member_work' );		 }	    
	    		public function getWid(){			 return self::$_data ['wid']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getInc_name(){			 return self::$_data ['inc_name']; 		}		public function getInc_indus(){			 return self::$_data ['inc_indus']; 		}		public function getInc_time(){			 return self::$_data ['inc_time']; 		}		public function getInc_job(){			 return self::$_data ['inc_job']; 		}		public function getInc_address(){			 return self::$_data ['inc_address']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setWid($value){ 			 self::$_data ['wid'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setInc_name($value){ 			 self::$_data ['inc_name'] = $value;			 return $this ; 		}		public function setInc_indus($value){ 			 self::$_data ['inc_indus'] = $value;			 return $this ; 		}		public function setInc_time($value){ 			 self::$_data ['inc_time'] = $value;			 return $this ; 		}		public function setInc_job($value){ 			 self::$_data ['inc_job'] = $value;			 return $this ; 		}		public function setInc_address($value){ 			 self::$_data ['inc_address'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_member_work  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_member_work		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['wid'] )) { 						self::$_where = array ('wid' => self::$_data ['wid'] );						unset(self::$_data['wid']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_member_work,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_member_work records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_member_work, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where wid = $this->_wid "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 