<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_template  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_template' );		 }	    
	    		public function getTpl_id(){			 return self::$_data ['tpl_id']; 		}		public function getTpl_title(){			 return self::$_data ['tpl_title']; 		}		public function getTpl_desc(){			 return self::$_data ['tpl_desc']; 		}		public function getDevelop(){			 return self::$_data ['develop']; 		}		public function getTpl_pic(){			 return self::$_data ['tpl_pic']; 		}		public function getTpl_path(){			 return self::$_data ['tpl_path']; 		}		public function getIs_selected(){			 return self::$_data ['is_selected']; 		}		public function getOn_time(){			 return self::$_data ['on_time']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setTpl_id($value){ 			 self::$_data ['tpl_id'] = $value;			 return $this ; 		}		public function setTpl_title($value){ 			 self::$_data ['tpl_title'] = $value;			 return $this ; 		}		public function setTpl_desc($value){ 			 self::$_data ['tpl_desc'] = $value;			 return $this ; 		}		public function setDevelop($value){ 			 self::$_data ['develop'] = $value;			 return $this ; 		}		public function setTpl_pic($value){ 			 self::$_data ['tpl_pic'] = $value;			 return $this ; 		}		public function setTpl_path($value){ 			 self::$_data ['tpl_path'] = $value;			 return $this ; 		}		public function setIs_selected($value){ 			 self::$_data ['is_selected'] = $value;			 return $this ; 		}		public function setOn_time($value){ 			 self::$_data ['on_time'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_template  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_template		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['tpl_id'] )) { 						self::$_where = array ('tpl_id' => self::$_data ['tpl_id'] );						unset(self::$_data['tpl_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_template,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_template records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_template, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where tpl_id = $this->_tpl_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 