<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_order_charge  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_order_charge' );		 }	    
	    		public function getOrder_id(){			 return self::$_data ['order_id']; 		}		public function getOrder_type(){			 return self::$_data ['order_type']; 		}		public function getPay_type(){			 return self::$_data ['pay_type']; 		}		public function getReturn_order_id(){			 return self::$_data ['return_order_id']; 		}		public function getObj_id(){			 return self::$_data ['obj_id']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getUsername(){			 return self::$_data ['username']; 		}		public function getPay_time(){			 return self::$_data ['pay_time']; 		}		public function getPay_money(){			 return self::$_data ['pay_money']; 		}		public function getOrder_status(){			 return self::$_data ['order_status']; 		}		public function getPay_info(){			 return self::$_data ['pay_info']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setOrder_id($value){ 			 self::$_data ['order_id'] = $value;			 return $this ; 		}		public function setOrder_type($value){ 			 self::$_data ['order_type'] = $value;			 return $this ; 		}		public function setPay_type($value){ 			 self::$_data ['pay_type'] = $value;			 return $this ; 		}		public function setReturn_order_id($value){ 			 self::$_data ['return_order_id'] = $value;			 return $this ; 		}		public function setObj_id($value){ 			 self::$_data ['obj_id'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setUsername($value){ 			 self::$_data ['username'] = $value;			 return $this ; 		}		public function setPay_time($value){ 			 self::$_data ['pay_time'] = $value;			 return $this ; 		}		public function setPay_money($value){ 			 self::$_data ['pay_money'] = $value;			 return $this ; 		}		public function setOrder_status($value){ 			 self::$_data ['order_status'] = $value;			 return $this ; 		}		public function setPay_info($value){ 			 self::$_data ['pay_info'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_order_charge  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_order_charge		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['order_id'] )) { 						self::$_where = array ('order_id' => self::$_data ['order_id'] );						unset(self::$_data['order_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_order_charge,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_order_charge records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_order_charge, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where order_id = $this->_order_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 