<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_member_bank  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_member_bank' );		 }	    
	    		public function getBank_id(){			 return self::$_data ['bank_id']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getReal_name(){			 return self::$_data ['real_name']; 		}		public function getCompany(){			 return self::$_data ['company']; 		}		public function getCard_id(){			 return self::$_data ['card_id']; 		}		public function getBank_name(){			 return self::$_data ['bank_name']; 		}		public function getBank_address(){			 return self::$_data ['bank_address']; 		}		public function getBank_sub_name(){			 return self::$_data ['bank_sub_name']; 		}		public function getCard_num(){			 return self::$_data ['card_num']; 		}		public function getBank_type(){			 return self::$_data ['bank_type']; 		}		public function getBind_status(){			 return self::$_data ['bind_status']; 		}		public function getOn_time(){			 return self::$_data ['on_time']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setBank_id($value){ 			 self::$_data ['bank_id'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setReal_name($value){ 			 self::$_data ['real_name'] = $value;			 return $this ; 		}		public function setCompany($value){ 			 self::$_data ['company'] = $value;			 return $this ; 		}		public function setCard_id($value){ 			 self::$_data ['card_id'] = $value;			 return $this ; 		}		public function setBank_name($value){ 			 self::$_data ['bank_name'] = $value;			 return $this ; 		}		public function setBank_address($value){ 			 self::$_data ['bank_address'] = $value;			 return $this ; 		}		public function setBank_sub_name($value){ 			 self::$_data ['bank_sub_name'] = $value;			 return $this ; 		}		public function setCard_num($value){ 			 self::$_data ['card_num'] = $value;			 return $this ; 		}		public function setBank_type($value){ 			 self::$_data ['bank_type'] = $value;			 return $this ; 		}		public function setBind_status($value){ 			 self::$_data ['bind_status'] = $value;			 return $this ; 		}		public function setOn_time($value){ 			 self::$_data ['on_time'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_member_bank  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_member_bank		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['bank_id'] )) { 						self::$_where = array ('bank_id' => self::$_data ['bank_id'] );						unset(self::$_data['bank_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_member_bank,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_member_bank records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_member_bank, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where bank_id = $this->_bank_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 