<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_task_cash_cove  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_task_cash_cove' );		 }	    
	    		public function getCash_rule_id(){			 return self::$_data ['cash_rule_id']; 		}		public function getStart_cove(){			 return self::$_data ['start_cove']; 		}		public function getEnd_cove(){			 return self::$_data ['end_cove']; 		}		public function getCove_desc(){			 return self::$_data ['cove_desc']; 		}		public function getOn_time(){			 return self::$_data ['on_time']; 		}		public function getModel_code(){			 return self::$_data ['model_code']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setCash_rule_id($value){ 			 self::$_data ['cash_rule_id'] = $value;			 return $this ; 		}		public function setStart_cove($value){ 			 self::$_data ['start_cove'] = $value;			 return $this ; 		}		public function setEnd_cove($value){ 			 self::$_data ['end_cove'] = $value;			 return $this ; 		}		public function setCove_desc($value){ 			 self::$_data ['cove_desc'] = $value;			 return $this ; 		}		public function setOn_time($value){ 			 self::$_data ['on_time'] = $value;			 return $this ; 		}		public function setModel_code($value){ 			 self::$_data ['model_code'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_task_cash_cove  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_task_cash_cove		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['cash_rule_id'] )) { 						self::$_where = array ('cash_rule_id' => self::$_data ['cash_rule_id'] );						unset(self::$_data['cash_rule_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_task_cash_cove,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_task_cash_cove records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_task_cash_cove, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where cash_rule_id = $this->_cash_rule_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 