<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_tag  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_tag' );		 }	    
	    		public function getTag_id(){			 return self::$_data ['tag_id']; 		}		public function getTagname(){			 return self::$_data ['tagname']; 		}		public function getTag_type(){			 return self::$_data ['tag_type']; 		}		public function getCache_time(){			 return self::$_data ['cache_time']; 		}		public function getTag_code(){			 return self::$_data ['tag_code']; 		}		public function getTpl_type(){			 return self::$_data ['tpl_type']; 		}		public function getOn_time(){			 return self::$_data ['on_time']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setTag_id($value){ 			 self::$_data ['tag_id'] = $value;			 return $this ; 		}		public function setTagname($value){ 			 self::$_data ['tagname'] = $value;			 return $this ; 		}		public function setTag_type($value){ 			 self::$_data ['tag_type'] = $value;			 return $this ; 		}		public function setCache_time($value){ 			 self::$_data ['cache_time'] = $value;			 return $this ; 		}		public function setTag_code($value){ 			 self::$_data ['tag_code'] = $value;			 return $this ; 		}		public function setTpl_type($value){ 			 self::$_data ['tpl_type'] = $value;			 return $this ; 		}		public function setOn_time($value){ 			 self::$_data ['on_time'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_tag  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_tag		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['tag_id'] )) { 						self::$_where = array ('tag_id' => self::$_data ['tag_id'] );						unset(self::$_data['tag_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_tag,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_tag records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_tag, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where tag_id = $this->_tag_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 