<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_invoice  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_invoice' );		 }	    
	    		public function getFpid(){			 return self::$_data ['fpid']; 		}		public function getUid(){			 return self::$_data ['uid']; 		}		public function getFp_title(){			 return self::$_data ['fp_title']; 		}		public function getFp_linxiren(){			 return self::$_data ['fp_linxiren']; 		}		public function getFp_zip(){			 return self::$_data ['fp_zip']; 		}		public function getFp_address(){			 return self::$_data ['fp_address']; 		}		public function getFp_mobile(){			 return self::$_data ['fp_mobile']; 		}		public function getFp_use(){			 return self::$_data ['fp_use']; 		}		public function getObj_type(){			 return self::$_data ['obj_type']; 		}		public function getObj_id(){			 return self::$_data ['obj_id']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setFpid($value){ 			 self::$_data ['fpid'] = $value;			 return $this ; 		}		public function setUid($value){ 			 self::$_data ['uid'] = $value;			 return $this ; 		}		public function setFp_title($value){ 			 self::$_data ['fp_title'] = $value;			 return $this ; 		}		public function setFp_linxiren($value){ 			 self::$_data ['fp_linxiren'] = $value;			 return $this ; 		}		public function setFp_zip($value){ 			 self::$_data ['fp_zip'] = $value;			 return $this ; 		}		public function setFp_address($value){ 			 self::$_data ['fp_address'] = $value;			 return $this ; 		}		public function setFp_mobile($value){ 			 self::$_data ['fp_mobile'] = $value;			 return $this ; 		}		public function setFp_use($value){ 			 self::$_data ['fp_use'] = $value;			 return $this ; 		}		public function setObj_type($value){ 			 self::$_data ['obj_type'] = $value;			 return $this ; 		}		public function setObj_id($value){ 			 self::$_data ['obj_id'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_invoice  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_invoice		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['fpid'] )) { 						self::$_where = array ('fpid' => self::$_data ['fpid'] );						unset(self::$_data['fpid']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_invoice,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_invoice records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_invoice, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where fpid = $this->_fpid "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 