<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_nav  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_nav' );		 }	    
	    		public function getNav_id(){			 return self::$_data ['nav_id']; 		}		public function getNav_url(){			 return self::$_data ['nav_url']; 		}		public function getNav_title(){			 return self::$_data ['nav_title']; 		}		public function getNav_style(){			 return self::$_data ['nav_style']; 		}		public function getListorder(){			 return self::$_data ['listorder']; 		}		public function getNewwindow(){			 return self::$_data ['newwindow']; 		}		public function getIshide(){			 return self::$_data ['ishide']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setNav_id($value){ 			 self::$_data ['nav_id'] = $value;			 return $this ; 		}		public function setNav_url($value){ 			 self::$_data ['nav_url'] = $value;			 return $this ; 		}		public function setNav_title($value){ 			 self::$_data ['nav_title'] = $value;			 return $this ; 		}		public function setNav_style($value){ 			 self::$_data ['nav_style'] = $value;			 return $this ; 		}		public function setListorder($value){ 			 self::$_data ['listorder'] = $value;			 return $this ; 		}		public function setNewwindow($value){ 			 self::$_data ['newwindow'] = $value;			 return $this ; 		}		public function setIshide($value){ 			 self::$_data ['ishide'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_nav  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_nav		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['nav_id'] )) { 						self::$_where = array ('nav_id' => self::$_data ['nav_id'] );						unset(self::$_data['nav_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_nav,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_nav records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_nav, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where nav_id = $this->_nav_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 