<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_task_wbzf  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_task_wbzf' );		 }	    
	    		public function getWbzf_id(){			 return self::$_data ['wbzf_id']; 		}		public function getTask_id(){			 return self::$_data ['task_id']; 		}		public function getWb_platform(){			 return self::$_data ['wb_platform']; 		}		public function getIs_focus(){			 return self::$_data ['is_focus']; 		}		public function getIs_comment(){			 return self::$_data ['is_comment']; 		}		public function getIs_at(){			 return self::$_data ['is_at']; 		}		public function getRepost_url(){			 return self::$_data ['repost_url']; 		}		public function getWb_content(){			 return self::$_data ['wb_content']; 		}		public function getWb_img(){			 return self::$_data ['wb_img']; 		}		public function getAt_num(){			 return self::$_data ['at_num']; 		}		public function getUnit_price(){			 return self::$_data ['unit_price']; 		}		public function getAssign(){			 return self::$_data ['assign']; 		}		public function getPay_amount(){			 return self::$_data ['pay_amount']; 		}		public function getFans_count(){			 return self::$_data ['fans_count']; 		}		public function getIs_repost(){			 return self::$_data ['is_repost']; 		}		public function getTen_content(){			 return self::$_data ['ten_content']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setWbzf_id($value){ 			 self::$_data ['wbzf_id'] = $value;			 return $this ; 		}		public function setTask_id($value){ 			 self::$_data ['task_id'] = $value;			 return $this ; 		}		public function setWb_platform($value){ 			 self::$_data ['wb_platform'] = $value;			 return $this ; 		}		public function setIs_focus($value){ 			 self::$_data ['is_focus'] = $value;			 return $this ; 		}		public function setIs_comment($value){ 			 self::$_data ['is_comment'] = $value;			 return $this ; 		}		public function setIs_at($value){ 			 self::$_data ['is_at'] = $value;			 return $this ; 		}		public function setRepost_url($value){ 			 self::$_data ['repost_url'] = $value;			 return $this ; 		}		public function setWb_content($value){ 			 self::$_data ['wb_content'] = $value;			 return $this ; 		}		public function setWb_img($value){ 			 self::$_data ['wb_img'] = $value;			 return $this ; 		}		public function setAt_num($value){ 			 self::$_data ['at_num'] = $value;			 return $this ; 		}		public function setUnit_price($value){ 			 self::$_data ['unit_price'] = $value;			 return $this ; 		}		public function setAssign($value){ 			 self::$_data ['assign'] = $value;			 return $this ; 		}		public function setPay_amount($value){ 			 self::$_data ['pay_amount'] = $value;			 return $this ; 		}		public function setFans_count($value){ 			 self::$_data ['fans_count'] = $value;			 return $this ; 		}		public function setIs_repost($value){ 			 self::$_data ['is_repost'] = $value;			 return $this ; 		}		public function setTen_content($value){ 			 self::$_data ['ten_content'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_task_wbzf  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_task_wbzf		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['wbzf_id'] )) { 						self::$_where = array ('wbzf_id' => self::$_data ['wbzf_id'] );						unset(self::$_data['wbzf_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_task_wbzf,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_task_wbzf records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_task_wbzf, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where wbzf_id = $this->_wbzf_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 