<?php defined ('IN_KEKE' ) or die ( 'Access Denied' );
	class Keke_witkey_session  extends Model {
	    protected static $_data = array ();
	     function  __construct(){ 			 parent::__construct ( 'witkey_session' );		 }	    
	    		public function getSession_id(){			 return self::$_data ['session_id']; 		}		public function getSession_expirse(){			 return self::$_data ['session_expirse']; 		}		public function getSession_data(){			 return self::$_data ['session_data']; 		}		public function getSession_ip(){			 return self::$_data ['session_ip']; 		}		public function getSession_uid(){			 return self::$_data ['session_uid']; 		}		public function getWhere(){			 return self::$_where; 		}
	    		public function setSession_id($value){ 			 self::$_data ['session_id'] = $value;			 return $this ; 		}		public function setSession_expirse($value){ 			 self::$_data ['session_expirse'] = $value;			 return $this ; 		}		public function setSession_data($value){ 			 self::$_data ['session_data'] = $value;			 return $this ; 		}		public function setSession_ip($value){ 			 self::$_data ['session_ip'] = $value;			 return $this ; 		}		public function setSession_uid($value){ 			 self::$_data ['session_uid'] = $value;			 return $this ; 		}		public function setWhere($value){ 			 self::$_where = $value;			 return $this; 		}		public function setData($array){ 			self::$_data = array_filter($array,array('Model','remove_null')); 			return $this; 		} 
	    /**		 * insert into  keke_witkey_session  ,or add new record		 * @return int last_insert_id		 */		function create($return_last_id=1){		 $res = $this->_db->insert ( $this->_tablename, self::$_data, $return_last_id, $this->_replace ); 		 $this->reset(); 			 return $res; 		 } 
	    /**		 * update table keke_witkey_session		 * @return int affected_rows		 */		function update() {				if ($this->getWhere()) { 					$res =  $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere());				} elseif (isset ( self::$_data ['session_id'] )) { 						self::$_where = array ('session_id' => self::$_data ['session_id'] );						unset(self::$_data['session_id']);						$res = $this->_db->update ( $this->_tablename, self::$_data, $this->getWhere() );				}				$this->reset();				return $res;		}
	    /**		 * query table: keke_witkey_session,if isset where return where record,else return all record		 * @return array 		 */		function query($fields = '*',$cache_time = 0){ 			 empty ( $fields ) and $fields = '*';			 if($this->getWhere()){ 				 $sql = "select $fields from $this->_tablename where ".$this->getWhere(); 			 }else{ 				 $sql = "select $fields from $this->_tablename"; 			 } 			 empty($fields) and $fields = '*'; 			 $this->reset();			 return $this->_db->cached ( $cache_time )->cache_data ( $sql );		 } 
	    /**		 * query count keke_witkey_session records,if iset where query by where 		 * @return int count records		 */		function count(){ 			 if($this->getWhere()){ 				 $sql = "select count(*) as count from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "select count(*) as count from $this->_tablename"; 			 } 			 $this->reset(); 			 return $this->_db->get_count ( $sql ); 		 } 
	    /**		 * delete table keke_witkey_session, if isset where delete by where 		 * @return int deleted affected_rows 		 */		function del(){ 			 if($this->getWhere()){ 				 $sql = "delete from $this->_tablename where ".$this->getWhere(); 			 } 			 else{ 				 $sql = "delete from $this->_tablename where session_id = $this->_session_id "; 			 } 			 $this->reset(); 			 return $this->_db->query ( $sql, Database::DELETE ); 		 } 
   } //end 